FROM baseImageYouWantToUse

LABEL maintainer="ksterx <kostonerx@gmail.com>"

ARG USERNAME=ksterx

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV TZ=Asia/Tokyo

# Set timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install apt packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    git \
    make \
    sudo

# Add user as sudoer
RUN useradd --create-home ${USERNAME} \
    && gpasswd -a ${USERNAME} sudo \
    && echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER ${USERNAME}
WORKDIR /home/${USERNAME}
RUN echo "set completion-ignore-case on" >> /home/${USERNAME}/.inputrc

WORKDIR /workspace
